# Generated by Django 5.2.7 on 2025-10-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('handler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('HIGH_TEMP', 'High Temperature'), ('OFFLINE', 'Offline'), ('ONLINE', 'Online')], max_length=20),
        ),
    ]
